version: "3"
services:
# My grafana service 
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      teleport:
        aliases:
          - grafana.teleport

  teleport-app:
    image: quay.io/gravitational/teleport:7
    entrypoint: /bin/sh
    container_name: teleport-app
    command: -c "/usr/bin/dumb-init teleport start -d  --insecure --roles=app --app-name=grafana-demo-2 --app-uri=http://grafana.teleport:3000 --token=$TOKEN --auth-server=$TELEPORT_APP_URI"
    mem_limit: 300m
    restart: always
    networks:
      teleport:
        aliases:
          - teleport-app.teleport

  postgres:
    image: postgres:latest
    entrypoint: /bin/sh
    container_name: postgres
    mem_limit: 300m
    networks:
      teleport:
        aliases:
          - postgres.teleport

  teleport-db:
    image: quay.io/gravitational/teleport:7
    entrypoint: /bin/sh
    container_name: teleport-db
    expose:
      - "3022"
    command: -c "/usr/bin/dumb-init teleport db start --token=$TOKEN --auth-server=$TELEPORT_APP_URI --name=teleport-pg-test --protocol=postgres --uri=postgres.teleport:5432"
    mem_limit: 300m
    restart: always
    networks:
      teleport:
        aliases:
          - teleport-db.teleport
  
# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
    external: true

networks:
  teleport:
